noSegments = 3
 inOutSegmentsIds = [0, 1]

 filename.0 = "Inlet"
 filename.1 = "Outlet"
 filename.2 = "LS_Channel.0"

 "body_segments.Inlet" = 0
 "body_segments.Outlet" = 1
 "body_segments.LsChannelMod" = 2

 BC.0 = 1022
 BC.1 = 4130
 BC.2 = 2222
